### ISSUE TITLE
"config.json" is a directory 

### ISSUE THREAD

**Issue by xiaotian1339** [kwaa/naive#1]
Sorry, after I pull and run, Docker cannot run, and the STATUS is Restart.
I tried looking for config.json to find the problem and found that "config.json" is a directory.

**Comment by kwaa** [comment]
Since this image doesn't copy config.json, this should be a problem with your environment.
Normally a `/etc/naive/config.json` configuration file should exist locally and be mapped to the container via `-v /etc/naive/config.json:/etc/naive/config.json`

**Comment by kwaa** [comment]
Are there any other questions? If not, I will close this issue later.
